### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by SirNate0** [MaxBondABE/batteries#1]
Hello, what is the license for this code?

**Comment by MaxBondABE** [comment]
I can post a public domain declaration later today. If you have a use for
it, I'd love to hear about it.

Cheers,
Max

**Comment by SirNate0** [comment]
Thanks.

Nothing amazing. I was just looking for how to make a torus in openscad and came across your library. Just wanted to give 3D printed chainmail a try. I'll try to give you an update about how it turns out.

**Comment by MaxBondABE** [comment]
@SirNate0 
Hi, sorry that this slipped my mind. Thanks for sharing, hope this helps.
